:book:[Docs] How-to: Channel-Based Automatic Updates
operator-framework/operator-controller pull request #1220
Opened 2024-09-05 15:33 UTC by perdasilva

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

2024-09-05 16:22 UTC, everettraven commented on docs/drafts/how-to-channel-based-upgrades.md
> +  installNamespace: argocd
There was a recent [PR](https://github.com/operator-framework/operator-controller/pull/1200) that put the `installNamespace` and `serviceAccount` fields under an `install` root field.

2024-09-05 19:05 UTC, OchiengEd requested changes
Looks good. I recommend slight rewording

2024-09-06 08:01 UTC, perdasilva commented on docs/drafts/how-to-channel-based-upgrades.md
> +Note that the `version` version range can also be set to further restrict the set of possible versions to upgrade to.
Nice! Thank you!!

I've updated it and tried to remove the preposition at the end? wdyt?

2024-09-06 14:15 UTC, everettraven commented on docs/drafts/how-to-channel-based-upgrades.md
> +      channel: [dev-preview, preview]
```suggestion
      channels: [dev-preview, preview]
```

2024-09-06 14:15 UTC, everettraven commented on docs/drafts/how-to-channel-based-upgrades.md
> +      channel: [stable] # Automatically upgrade to the latest version found in ‘stable’
```suggestion
      channels: [stable] # Automatically upgrade to the latest version found in ‘stable’
```

2024-09-06 14:32 UTC, perdasilva commented on docs/drafts/how-to-channel-based-upgrades.md
> +      channel: [stable] # Automatically upgrade to the latest version found in ‘stable’
Thank you! Fixed ^^

2024-09-06 14:32 UTC, perdasilva commented on docs/drafts/how-to-channel-based-upgrades.md
> +      channel: [dev-preview, preview]
Thank you! Fixed ^^

2024-09-06 20:15 UTC, everettraven approved these changes

2024-09-07 01:19 UTC, joelanford approved these changes

2024-09-07 01:28 UTC, merged