📖 [Docs] Document tilt-support install
operator-framework/operator-controller pull request #1236
Opened 2024-09-09 17:49 UTC by bentito

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

2024-09-09 19:44 UTC, LalatenduMohanty requested changes

2024-09-09 19:44 UTC, LalatenduMohanty commented on tilt.md
> +You must install the tilt-support repo one level up from this repo
I do not think this text `one level up from this repo` is adding any extra value as the below command clearly mentions which repo to clone.

2024-09-09 20:01 UTC, LalatenduMohanty commented
Can we add a link of this document in https://github.com/operator-framework/operator-controller/blob/main/docs/drafts/developer.md? As both of these docs should be at least linked if not consolidated.

2024-09-10 11:57 UTC, bentito commented
> Can we add a link of this document in https://github.com/operator-framework/operator-controller/blob/main/docs/drafts/developer.md? As both of these docs should be at least linked if not consolidated.

I think the idea to simply merging this text about tilt into a section of the developer.md doc is a good one. I'd like to just finish up this PR so we have better text to merge. We can do the tilt -> developer merge in a follow up PR

2024-09-10 12:03 UTC, bentito commented
Created this issue to track combining tilt.md into developer.md: https://github.com/operator-framework/operator-controller/issues/1242

2024-09-10 12:15 UTC, joelanford approved these changes

2024-09-10 12:39 UTC, merged