🐛 main.go: improve logging for configuration of global auth
operator-framework/operator-controller pull request #1316
Opened 2024-09-26 20:12 UTC by joelanford

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

2024-09-26 20:17 UTC, tmshort approved these changes
/lgtm

2024-09-26 20:17 UTC, everettraven approved these changes

2024-09-26 20:24 UTC, LalatenduMohanty requested changes

2024-09-26 20:24 UTC, LalatenduMohanty commented on cmd/manager/main.go
> +		logger.Error(err, "unable to stat auth file path", "path", authFilePath)
`unable to stat auth file path` is kind of meaning less in a way. How would the user know that we are talking about os.stat and what does that mean.

2024-09-26 20:25 UTC, LalatenduMohanty commented
/hold as the existing lgtm would lead to merging of the PR and I  have a review comment https://github.com/operator-framework/operator-controller/pull/1316#discussion_r1777692583 which should be addressed.

2024-09-27 12:09 UTC, LalatenduMohanty approved these changes
/lgtm

2024-09-27 12:10 UTC, LalatenduMohanty commented
/hold cancel

2024-09-27 12:46 UTC, merged