⚠ remove olm.bundle.mediatype property and clusterextension support for…
operator-framework/operator-controller pull request #822
Opened 2024-05-02 21:29 UTC by joelanford

… plain+v0

# Description

## Reviewer Checklist

- [ ] API Go Documentation
- [ ] Tests: Unit Tests (and E2E Tests, if appropriate)
- [ ] Comprehensive Commit Messages
- [ ] Links to related GitHub Issue(s)

2024-05-02 21:35 UTC, everettraven requested changes
Should probably remove the plain-v0 entries under testdata/bundles as well

(Apologies if I missed the removal - on GH mobile so it's entirely possible I missed it being removed)

2024-05-03 10:23 UTC, m1kola reviewed
What do we do with [this demo](https://github.com/operator-framework/operator-controller/blob/5985cce3b9dd8d9d0f53b926c242202d9a3dbccb/docs/demos/coast-to-coast-q4-2023.md)? It seem to rely on `plain+v0` bundle types. I think this PR will break the demo.

2024-05-03 10:23 UTC, m1kola commented on internal/controllers/clusterextension_controller.go
> +	bundleProvisioner := "core-rukpak-io-registry"
Nit: Maybe let's get rid of `bundleProvisioner` variable and of param in `r.GenerateExpectedBundleDeployment`?

Will help to reduce the noise in `reconcile` a little bit.

2024-05-03 14:53 UTC, everettraven approved these changes

2024-05-03 14:55 UTC, everettraven commented
>What do we do with [this demo](https://github.com/operator-framework/operator-controller/blob/5985cce3b9dd8d9d0f53b926c242202d9a3dbccb/docs/demos/coast-to-coast-q4-2023.md)? It seem to rely on plain+v0 bundle types. I think this PR will break the demo.

I'd vote to either:
- Remove it entirely since we have shifted direction quite significantly from when that was written
- Update it accordingly

I personally am leaning towards removal since we are going to need to write new coast-to-coast documentation/tutorials for the new state of the world

2024-05-03 16:34 UTC, joelanford commented
> I personally am leaning towards removal

I'll remove it. I was having similar thoughts as well.

2024-05-03 16:51 UTC, m1kola approved these changes

2024-05-03 17:11 UTC, merged